steps:
- task: checkmarx.cxsast.cx-scan-task.Security static source code analysis@2019
  displayName: 'Security static source code analysis'
  inputs:
    CheckmarxService: CxAPAC
    projectName: 'KMD'
    fullTeamName: 'CxServer\SP'
    incScan: false
    fileExtension: '!*.DS_Store, !*.ipr,     !*.iws, !*.bak,    !*.tmp,     !*.aac,      !*.aif,      !*.iff,     !*.m3u,   !*.mid,   !*.mp3, !*.mpa,    !*.ra,        !*.wav,      !*.wma,      !*.3g2,     !*.3gp,   !*.asf,   !*.asx, !*.avi,    !*.flv,       !*.mov,     !*.mp4,      !*.mpg,     !*.rm,    !*.swf,   !*.vob, !*.wmv,    !*.bmp,       !*.gif,       !*.jpg,      !*.png,     !*.psd,   !*.tif,   !*.swf, !*.jar,    !*.zip,       !*.rar,      !*.exe,      !*.dll,     !*.pdb,   !*.7z,    !*.gz, !*.tar.gz, !*.tar,       !*.gz,       !*.ahtm,     !*.ahtml,   !*.fhtml, !*.hdm, !*.hdml,   !*.hsql,      !*.ht,      !*.hta,      !*.htc,     !*.htd,   !*.war,   !*.ear, !*.htmls,  !*.ihtml,     !*.mht,      !*.mhtm,     !*.mhtml,   !*.ssi,   !*.stm, !*.stml,   !*.ttml,      !*.txn,      !*.xhtm,     !*.xhtml,   !*.class, !*.iml'
    high: 15
    medium: 10
    low: 15